package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/mkt36z/cli/internal/api"
	"github.com/mkt36z/cli/internal/config"
	"github.com/mkt36z/cli/internal/local"
	"github.com/mkt36z/cli/internal/output"
	"github.com/mkt36z/cli/internal/ui"
)

var (
	genCount          int
	genAwarenessLevel string
	genChannel        string
	genLang           string
)

var validGenTypes = []string{
	"headline", "email", "post", "brief", "copy", "landing-page",
	"video-script", "ad-creative", "battle-card", "seo-content",
	"one-pager", "case-study",
}

var generateCmd = &cobra.Command{
	Use:   "generate <type> <topic>",
	Short: "Generate marketing content",
	Long: fmt.Sprintf(`Generate high-converting marketing content using AI agents.

  Types: %s

  Examples:
    mkt36z generate headline "AI-powered CRM for startups"
    mkt36z generate email "welcome sequence" --count 3
    mkt36z generate post "product launch" --channel linkedin
    mkt36z generate landing-page "SaaS pricing page"

  Output includes:
    - Content generated by the Content Engine agent
    - QA score (0-100) from the Quality Guardian agent
    - Framework citations

  Use --json for machine-readable output.`, strings.Join(validGenTypes, ", ")),
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		contentType := args[0]

		// Validate type
		if !isValidGenType(contentType) {
			return fmt.Errorf("invalid content type: %s\n  Valid types: %s", contentType, strings.Join(validGenTypes, ", "))
		}

		// Build topic from remaining args
		topic := ""
		if len(args) > 1 {
			topic = strings.Join(args[1:], " ")
		}

		// Check for stdin
		if topic == "" {
			if data, err := output.ReadStdin(); err == nil && data != "" {
				topic = data
			}
		}

		if topic == "" {
			return fmt.Errorf("topic is required. Usage: mkt36z generate %s \"your topic\"", contentType)
		}

		// Local pre-check
		precheck := local.PreCheck(topic)
		if len(precheck.Warnings) > 0 && flagVerbose > 0 {
			fmt.Fprintf(os.Stderr, "Pre-check warnings:\n")
			for _, w := range precheck.Warnings {
				fmt.Fprintf(os.Stderr, "  - %s\n", w)
			}
			fmt.Fprintln(os.Stderr)
		}

		// Load API key
		key, err := api.LoadAPIKey()
		if err != nil || key == "" {
			return fmt.Errorf("not authenticated. Run `mkt36z auth login` first")
		}

		// Load user context
		userCtx := loadUserContext()

		// Build request body
		reqBody := map[string]interface{}{
			"topic": topic,
			"options": map[string]interface{}{
				"count":          genCount,
				"awarenessLevel": genAwarenessLevel,
				"channel":        genChannel,
				"lang":           genLang,
			},
		}
		if userCtx != nil {
			reqBody["context"] = userCtx
		}

		bodyJSON, _ := json.Marshal(reqBody)

		// Make streaming request
		client := api.NewStreamingClient(flagAPIURL, key)
		path := fmt.Sprintf("/api/v1/generate/%s", contentType)

		// Start spinner for non-JSON mode
		var sp *ui.Spinner
		if !flagJSON {
			sp = ui.NewSpinner(fmt.Sprintf("Generating %s...", contentType))
		}

		resp, err := client.Do(context.Background(), "POST", path, bytes.NewReader(bodyJSON))
		if err != nil {
			if sp != nil {
				sp.Stop("")
			}
			return err
		}

		// Process SSE stream — buffer content, update spinner with progress
		var content strings.Builder
		var qaScore map[string]interface{}

		for event := range api.StreamSSE(context.Background(), resp) {
			switch event.Type {
			case api.EventContentChunk:
				var chunk struct {
					Content string `json:"content"`
				}
				if json.Unmarshal([]byte(event.Data), &chunk) == nil {
					content.WriteString(chunk.Content)
				}

			case api.EventQAScore:
				if json.Unmarshal([]byte(event.Data), &qaScore) != nil {
					qaScore = nil
				}

			case api.EventAgentProgress:
				if sp != nil {
					var progress struct {
						Message string `json:"message"`
					}
					if json.Unmarshal([]byte(event.Data), &progress) == nil {
						sp.UpdateMessage(progress.Message)
					}
				}

			case api.EventError:
				if sp != nil {
					sp.Stop("")
				}
				var errData struct {
					Error string `json:"error"`
				}
				if json.Unmarshal([]byte(event.Data), &errData) == nil {
					return fmt.Errorf("agent error: %s", errData.Error)
				}

			case api.EventDone:
				// Stream complete
			}
		}

		// Build final status and stop spinner
		qaScoreVal := 0
		if qaScore != nil {
			if t, ok := qaScore["total"].(float64); ok {
				qaScoreVal = int(t)
			}
		}
		if sp != nil {
			finalMsg := "Done"
			if qaScore != nil {
				total, _ := qaScore["total"].(float64)
				pass, _ := qaScore["pass"].(bool)
				status := "PASS"
				if !pass {
					status = "NEEDS IMPROVEMENT"
				}
				finalMsg = fmt.Sprintf("Done — QA Score: %.0f/100 (%s)", total, status)
			}
			sp.Stop(ui.CheckMark + " " + finalMsg)
		}

		// Save to history
		_ = local.AppendHistory(local.HistoryEntry{
			Command: "generate " + contentType,
			Input:   topic,
			Output:  content.String(),
			QAScore: qaScoreVal,
		})

		// Output
		if flagJSON {
			result := map[string]interface{}{
				"type":    contentType,
				"topic":   topic,
				"content": content.String(),
			}
			if qaScore != nil {
				result["qa_score"] = qaScore
			}
			out, _ := json.MarshalIndent(result, "", "  ")
			fmt.Println(string(out))
		} else {
			// Render buffered content as formatted markdown
			rendered, err := ui.RenderMarkdown(content.String())
			if err != nil {
				fmt.Print(content.String())
			} else {
				fmt.Print(rendered)
			}
		}

		return nil
	},
}

func init() {
	generateCmd.Flags().IntVar(&genCount, "count", 5, "Number of variations to generate")
	generateCmd.Flags().StringVar(&genAwarenessLevel, "awareness-level", "", "Target awareness level (1-5)")
	generateCmd.Flags().StringVar(&genChannel, "channel", "", "Target channel (linkedin, twitter, email, etc.)")
	generateCmd.Flags().StringVar(&genLang, "lang", "", "Output language code (e.g., es, fr, de)")
	rootCmd.AddCommand(generateCmd)
}

func isValidGenType(t string) bool {
	for _, v := range validGenTypes {
		if v == t {
			return true
		}
	}
	return false
}

// loadUserContext gathers all populated context files for the API request.
func loadUserContext() map[string]interface{} {
	ctx := make(map[string]interface{})

	ctxMap := map[config.ContextType]interface{}{
		config.ContextBusiness:     &config.BusinessContext{},
		config.ContextProduct:      &config.ProductContext{},
		config.ContextICP:          &config.ICPContext{},
		config.ContextCompetitive:  &config.CompetitiveContext{},
		config.ContextBrandVoice:   &config.BrandVoice{},
		config.ContextChannels:     &config.ChannelsContext{},
		config.ContextContentSEO:   &config.ContentSEOContext{},
		config.ContextSales:        &config.SalesContext{},
		config.ContextGoals:        &config.GoalsContext{},
		config.ContextLanguageBank: &config.LanguageBankContext{},
		config.ContextProofStack:   &config.ProofStackContext{},
		config.ContextAntiPatterns: &config.AntiPatternsContext{},
	}

	keyMap := map[config.ContextType]string{
		config.ContextBusiness:     "business",
		config.ContextProduct:      "product",
		config.ContextICP:          "icp",
		config.ContextCompetitive:  "competitive",
		config.ContextBrandVoice:   "brandVoice",
		config.ContextChannels:     "channels",
		config.ContextContentSEO:   "contentSeo",
		config.ContextSales:        "sales",
		config.ContextGoals:        "goals",
		config.ContextLanguageBank: "languageBank",
		config.ContextProofStack:   "proofStack",
		config.ContextAntiPatterns: "antiPatterns",
	}

	for ct, target := range ctxMap {
		if config.ContextFileExists(ct) {
			if err := config.LoadContext(ct, target); err == nil {
				ctx[keyMap[ct]] = target
			}
		}
	}

	if len(ctx) == 0 {
		return nil
	}
	return ctx
}
