FROM alpine:3.19 AS certs
RUN apk add --no-cache ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY mkt36z /usr/local/bin/mkt36z
ENTRYPOINT ["/usr/local/bin/mkt36z"]
